#!/usr/bin/env bash
# wal-to-qml.sh — Convert pywal's colors.json into config/ColorsWal.qml
#
# pywal writes a JSON file with 16 ANSI colors (color0–color15) plus
# special.background / special.foreground / special.cursor.
# We map those onto the same property names used by config/Colors.qml,
# so ColorScheme.qml can switch between the static fallback and this
# generated file transparently.
#
# Usage: ./wal-to-qml.sh [colors.json path] [output .qml path]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

WAL_JSON="${1:-$HOME/.cache/wal/colors.json}"
OUT_QML="${2:-$REPO_ROOT/config/ColorsWal.qml}"

log()  { echo -e "\e[34m[INFO]\e[0m  $*"; }
ok()   { echo -e "\e[32m[OK]\e[0m    $*"; }
err()  { echo -e "\e[31m[ERROR]\e[0m $*" >&2; exit 1; }

[[ -f "$WAL_JSON" ]] || err "pywal colors not found at $WAL_JSON — run 'wal -i /path/to/wallpaper' first."
command -v jq &>/dev/null || err "jq is required. Install it: sudo pacman -S jq  /  sudo apt install jq"

log "Reading palette from $WAL_JSON"

# ── Extract colors via jq ──────────────────────────────────
bg=$(jq -r '.special.background' "$WAL_JSON")
fg=$(jq -r '.special.foreground' "$WAL_JSON")

c0=$(jq -r '.colors.color0'  "$WAL_JSON")   # black / bg-alt
c1=$(jq -r '.colors.color1'  "$WAL_JSON")   # red
c2=$(jq -r '.colors.color2'  "$WAL_JSON")   # green
c3=$(jq -r '.colors.color3'  "$WAL_JSON")   # yellow
c4=$(jq -r '.colors.color4'  "$WAL_JSON")   # blue
c7=$(jq -r '.colors.color7'  "$WAL_JSON")   # white / fg-muted
c8=$(jq -r '.colors.color8'  "$WAL_JSON")   # bright black / surface
c12=$(jq -r '.colors.color12' "$WAL_JSON")  # bright blue / accent

# ── Validate we got hex colors ────────────────────────────
for c in "$bg" "$fg" "$c0" "$c1" "$c2" "$c3" "$c4" "$c8" "$c12"; do
    [[ "$c" =~ ^#[0-9a-fA-F]{6}$ ]] || err "Unexpected color value: $c"
done

# ── Derive the same property set as config/Colors.qml ──────
# Mapping rationale:
#   colBg      ← special.background
#   colBgAlt   ← color0  (terminal black, usually darkest)
#   colSurface ← color8  (bright black, slightly lighter than bg)
#   colBorder  ← color7  (muted white, works as a subtle border)
#   colFg      ← special.foreground
#   colFgMuted ← color7
#   colAccent  ← color12 (bright blue — closest to UI accent role)
#   colBlue    ← color4
#   colGreen   ← color2
#   colYellow  ← color3
#   colRed     ← color1
#   colError   ← color1 (darkened via alpha at usage site)

log "Generating $OUT_QML"

cat > "$OUT_QML" << EOF
// config/ColorsWal.qml — AUTO-GENERATED by scripts/wal-to-qml.sh
// Do not edit manually — regenerate with: ./scripts/wal-gen.sh <wallpaper>
//
// Source: $WAL_JSON
// Generated: $(date -Iseconds)

pragma Singleton
import QtQuick

QtObject {
    // ─── Base ───────────────────────────────────────────────
    readonly property color colBg:      "$bg"
    readonly property color colBgAlt:   "$c0"
    readonly property color colSurface: "$c8"
    readonly property color colBorder:  "$c7"

    // ─── Foreground ─────────────────────────────────────────
    readonly property color colFg:      "$fg"
    readonly property color colFgMuted: "$c7"

    // ─── Accent ─────────────────────────────────────────────
    readonly property color colAccent:  "$c12"
    readonly property color colBlue:    "$c4"
    readonly property color colGreen:   "$c2"
    readonly property color colYellow:  "$c3"
    readonly property color colRed:     "$c1"
    readonly property color colError:   "$c1"

    // ─── Opacity helpers ────────────────────────────────────
    function withAlpha(c, a) { return Qt.rgba(c.r, c.g, c.b, a) }
}
EOF

ok "Wrote $OUT_QML"
ok "Reload QuickShell to apply: ./scripts/reload.sh"
